name: 'Web Request Action'
description: 'Send Web Request'
author: 'Satak'
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  url:
    description: 'Web request URL endpoint'
    required: true
  method:
    description: 'Web request method (`GET`, `POST`, `PUT`, `PATCH`, `DELETE`)'
    required: true
    default: GET
  payload:
    description: Web request payload in JSON format
    required: false
  headers:
    description: Web request headers in JSON format
    required: false
  username:
    description: username for BASIC auth
    required: false
  password:
    description: password for BASIC auth
    required: false
outputs:
  output:
    description: 'data output from the web request'
runs:
  using: 'node16'
  main: 'dist/index.js'
