name: "Poll Endpoint"
description: "A GitHub Action that polls a specified HTTP endpoint until it becomes available. Based on emilioschepis/wait-for-endpoint"
author: "Artem Kustikov"
branding:
  icon: clock
  color: green
inputs:
  url:
    description: The URL to poll
    required: true
  method:
    description: The HTTP method to use
    required: false
    default: GET
  authorization:
    description: If needed, the full value of the Authorization header (e.g. Bearer [token])
    required: false
  expectStatus:
    description: The HTTP status that is expected
    required: false
    default: "200"
  expectBody:
    description: Response body that is expected
    required: false
  expectBodyRegex:
    description: Regex to match expected response body
    required: false
  timeout:
    description: The maximum time the polling is allowed to run for (in milliseconds)
    required: false
    default: "60000"
  interval:
    description: The interval at which the polling should happen (in milliseconds)
    required: false
    default: "1000"
outputs:
  response:
    description: "HTTP Response Content"
  headers:
    description: "HTTP Response Headers"
runs:
  using: node16
  main: dist/index.js
