name: 'Request Previewable Access'
description: 'Request to allow deploying connector in preview mode'

inputs:
  version:
    description: 'ConnectorStaged version to reference'
    required: true
  access_token:
    description: 'commercetools access token'
    required: true
  ct_region:
    description: 'commercetools region'
    required: true
  connector_key:
    description: 'commercetools ConnectorStaged key (also used as deployment prefix)'
    required: true
outputs:
  response:
    description: 'Connector after previewable access is granted'
    value: ${{ steps.ct_check_connector_previewable.outputs.response }}

runs:
  using: "composite"
  steps:
    - name: Request ConnectorStaged Previewable access
      id: ct_update_connector_previewable
      uses: ./.github/actions/webrequest-action
      with:
        url: https://connect.${{ inputs.ct_region }}.commercetools.com/connectors/drafts/key=${{ inputs.connector_key }}
        method: POST
        headers: '{"Authorization": "Bearer ${{ inputs.access_token }}"}'
        payload: '{"version":${{ inputs.version }},"actions":[{"action":"updatePreviewable"}]}'
    - name: Check ConnectorStaged Previewable access state
      id: ct_check_connector_previewable
      uses: ./.github/actions/poll-endpoint
      with:
        url: https://connect.${{ inputs.ct_region }}.commercetools.com/connectors/drafts/key=${{ inputs.connector_key }}
        method: GET
        authorization: 'Bearer ${{ inputs.access_token }}'
        expectStatus: 200
        expectBodyRegex: \"isPreviewable\":\"true\"
        timeout: 900000
        interval: 15000