name: 'Postman tests action'
description: 'Runs postman tests'

inputs:
  postman_collection_json:
    description: 'the name of the json file with the postman collection to run'
    required: true
  ct_client_id:
    description: 'commercetools client id for running tests'
    required: true
  ct_secret:
    description: 'commercetools secret for running tests'
    required: true
  ct_region:
    description: 'commercetools region'
    required: true
  ct_project_id:
    description: 'commercetools project id'
    required: true
  ee_wallet_url:
    description: 'EagleEye API Wallet URL'
    required: false
  ee_pos_url:
    description: 'EagleEye API POS URL'
    required: false
  ee_resources_url:
    description: 'EagleEye API Resources URL'
    required: false
  ee_client_id:
    description: 'EagleEye API client id'
    required: true
  ee_client_secret:
    description: 'EagleEye API client secret'
    required: true

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: yarn
        cache-dependency-path: ./integration/yarn.lock
    - name: Install newman
      run: |
        yarn global add newman newman-reporter-htmlextra
      shell: bash
    - name: Set current date as env variable
      run: echo "current_date=$(date +'%Y-%m-%dT%H_%M_%S')" >> $GITHUB_OUTPUT
      shell: bash
      id: date_output
    - name: Run e2e tests
      env:
        POSTMAN_COLLECTION: ${{ inputs.postman_collection_json }}
        CT_CLIENT_ID: ${{ inputs.ct_client_id }}
        CT_SECRET: ${{ inputs.ct_secret }}
        CT_REGION: ${{ inputs.ct_region }}
        CT_PROJECT_ID: ${{ inputs.ct_project_id }}
        EE_POS_URL: ${{ inputs.ee_pos_url }}
        EE_WALLET_URL: ${{ inputs.ee_wallet_url }}
        EE_CLIENT_ID: ${{ inputs.ee_client_id }}
        EE_CLIENT_SECRET: ${{ inputs.ee_client_secret }}
      run: |
        newman run "$POSTMAN_COLLECTION" \
          -r htmlextra \
          --reporter-htmlextra-export "newman/htmlreport-${CT_PROJECT_ID}.html" \
          --env-var "client_id=${CT_CLIENT_ID}" \
          --env-var "client_secret=${CT_SECRET}" \
          --env-var "auth_url=https://auth.${CT_REGION}.commercetools.com" \
          --env-var "host=https://api.${CT_REGION}.commercetools.com" \
          --env-var "project-key=${CT_PROJECT_ID}" \
          --env-var "pos_url=${EE_POS_URL}" \
          --env-var "wallet_url=${EE_WALLET_URL}" \
          --env-var "schemeId=1653843" \
          --env-var "ee_client_id=${EE_CLIENT_ID}" \
          --env-var "ee_client_secret=${EE_CLIENT_SECRET}"
      shell: bash
      working-directory: ./integration/test
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: E2E-reports-${{steps.date_output.outputs.current_date}}
        path: integration/test/newman