nodeLinker: node-modules

packageExtensions:
  '@commitlint/load@*':
    dependencies:
      '@types/node': '*'
      'typescript': '*'
  'nest-commander@*':
    dependencies:
      '@types/inquirer': '8.2.12'
