name: Deploy integration to CT Connect
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Deploy to connect environment
        required: true
        options:
          - dev
          - staging
      dev_to_staging:
        type: boolean
        description: Deploy dev connector to staging
        required: false
        default: false
      connector_key:
        type: string
        description: ConnectorStaged key (override)
        required: false
        default: ''
      config_override:
        type: string
        description: Stringified and escaped JSON to override all integration configurations
        required: false

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      connector_key: ${{ steps.set-connector-key.outputs.connector_key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set connector_key based on environment
        id: set-connector-key
        run: |
          if [[ -n "${{ github.event.inputs.connector_key }}" ]]; then
            echo "::set-output name=connector_key::${{ github.event.inputs.connector_key }}"
          elif [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "::set-output name=connector_key::eagleeye-integration-testing"
          elif [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            echo "::set-output name=connector_key::eagleeye-commercetools-integration"
          fi
  ct-authorize:
    name: 'Authenticate with commercetools'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      access_token: ${{ fromJSON(steps.authenticate.outputs.output).data.access_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate
        id: authenticate
        uses: ./.github/actions/connect/authenticate
        with:
          ct_api_client_id: ${{ secrets.CT_CLIENT_ID }}
          ct_api_client_secret: ${{ secrets.CT_CLIENT_SECRET }}
          ct_region: ${{ vars.CT_REGION }}
  ct-authorize-dev-to-staging:
    name: 'Authenticate with commercetools (dev to staging)'
    runs-on: ubuntu-latest
    environment: staging
    #if: ${{ github.event.inputs.environment == 'dev' && github.event.inputs.dev_to_staging == 'true' }} 
    outputs:
      access_token: ${{ fromJSON(steps.authenticate.outputs.output).data.access_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate
        id: authenticate
        uses: ./.github/actions/connect/authenticate
        with:
          ct_api_client_id: ${{ secrets.CT_CLIENT_ID }}
          ct_api_client_secret: ${{ secrets.CT_CLIENT_SECRET }}
          ct_region: ${{ vars.CT_REGION }}
  ct-update-tag:
    name: 'Update Connector Tag'
    runs-on: ubuntu-latest
    needs: [ 'ct-authorize', 'setup' ]
    environment: ${{ github.event.inputs.environment }}
    outputs:
      connector: ${{ steps.update-tag.outputs.output }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get and update Connector
        id: update-tag
        uses: ./.github/actions/connect/update-tag
        with:
          tag: ${{ github.ref_name }}
          access_token: ${{ needs.ct-authorize.outputs.access_token }}
          ct_region: ${{ vars.CT_REGION }}
          connector_key: ${{ needs.setup.outputs.connector_key }}
  ct-publish:
    name: 'Publish Connector (Previewable/Private)'
    runs-on: ubuntu-latest
    needs: [ 'ct-authorize', 'ct-update-tag', 'setup' ]
    environment: ${{ github.event.inputs.environment }}
    outputs:
      connector: ${{ steps.publish.outputs.response }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish
        id: publish
        uses: ./.github/actions/connect/publish
        with:
          version: ${{ fromJSON(needs.ct-update-tag.outputs.connector).data.version }}
          access_token: ${{ needs.ct-authorize.outputs.access_token }}
          ct_region: ${{ vars.CT_REGION }}
          connector_key: ${{ needs.setup.outputs.connector_key }}
          github_env: ${{ github.event.inputs.environment }}
          dev_to_staging: ${{ github.event.inputs.dev_to_staging }}
  ct-undeploy:
    name: 'Check and Undeploy Connector'
    runs-on: ubuntu-latest
    needs: [ 'ct-authorize', 'ct-publish', 'setup', 'ct-authorize-dev-to-staging' ]
    environment: ${{ github.event.inputs.dev_to_staging == 'true' && 'staging' || github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check and Undeploy Connector
        id: undeploy
        uses: ./.github/actions/connect/undeploy
        with:
          access_token: ${{ github.event.inputs.dev_to_staging == 'true' && needs.ct-authorize-dev-to-staging.outputs.access_token || needs.ct-authorize.outputs.access_token }}
          ct_project_key: ${{ vars.CT_PROJECT_KEY }}
          ct_region: ${{ vars.CT_REGION }}
          connect_env: ${{ github.event.inputs.dev_to_staging == 'true' && 'staging' || github.event.inputs.environment }}
          connector_key: ${{ needs.setup.outputs.connector_key }}
  ct-deploy:
    name: 'Deploy Connector'
    runs-on: ubuntu-latest
    needs: [ 'ct-authorize', 'ct-publish', 'ct-undeploy', 'setup', 'ct-authorize-dev-to-staging' ]
    environment: ${{ github.event.inputs.dev_to_staging == 'true' && 'staging' || github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy Connector
        id: deploy
        uses: ./.github/actions/connect/deploy
        with:
          version: ${{ fromJSON(needs.ct-publish.outputs.connector).version }}
          access_token: ${{ github.event.inputs.dev_to_staging == 'true' && needs.ct-authorize-dev-to-staging.outputs.access_token || needs.ct-authorize.outputs.access_token }}
          is_previewable: ${{ github.event.inputs.dev_to_staging == 'false' }}
          connect_env: ${{ github.event.inputs.dev_to_staging == 'true' && 'staging' || github.event.inputs.environment }}
          connector_key: ${{ needs.setup.outputs.connector_key }}
          ct_api_client_id: ${{ secrets.CT_CLIENT_ID }}
          ct_api_client_secret: ${{ secrets.CT_CLIENT_SECRET }}
          ct_region: ${{ vars.CT_REGION }}
          ct_project_key: ${{ vars.CT_PROJECT_KEY }}
          ct_scopes: ${{ vars.CT_SCOPES }}
          ct_cart_type_key: ${{ vars.CT_CART_TYPE_KEY }}
          ee_client_id: ${{ secrets.EE_CLIENT_ID }}
          ee_client_secret: ${{ secrets.EE_CLIENT_SECRET }}
          config_override: ${{ github.event.inputs.config_override }}
          ee_pos_url: ${{ vars.EE_POS_URL }}
          shipping_method_map: ${{ vars.SHIPPING_METHOD_MAP }}
          ee_incoming_identifier: ${{ vars.EE_INCOMING_IDENTIFIER }}
          ee_parent_incoming_identifier: ${{ vars.EE_PARENT_INCOMING_IDENTIFIER }}
          ee_exclude_unidentified_customers: ${{ vars.EE_EXCLUDE_UNIDENTIFIED_CUSTOMERS }}
          ee_use_item_sku: ${{ vars.EE_USE_ITEM_SKU }}
          ee_api_client_timeout: ${{ vars.EE_API_CLIENT_TIMEOUT }}
          always_store_basket_in_custom_object: ${{ vars.ALWAYS_STORE_BASKET_IN_CUSTOM_OBJECT }}
          circuit_breaker_timeout: ${{ vars.CIRCUIT_BREAKER_TIMEOUT }}
          circuit_breaker_reset_timeout: ${{ vars.CIRCUIT_BREAKER_RESET_TIMEOUT }}
          circuit_breaker_error_threshold_percentage: ${{ vars.CIRCUIT_BREAKER_ERROR_THRESHOLD_PERCENTAGE }}
          circuit_breaker_enabled: ${{ vars.CIRCUIT_BREAKER_ENABLED }}
          ctp_disabled_events: ${{ vars.CTP_DISABLED_EVENTS }}
          basket_cleanup_query_limit: ${{ vars.BASKET_CLEANUP_QUERY_LIMIT }}
          basket_cleanup_older_than_value: ${{ vars.BASKET_CLEANUP_OLDER_THAN_VALUE }}
          basket_cleanup_older_than_unit: ${{ vars.BASKET_CLEANUP_OLDER_THAN_UNIT }}
  e2e-tests:
    name: 'Running E2E tests'
    if: ${{ github.event.inputs.environment != 'staging' && github.event.inputs.dev_to_staging == 'false' }}
    runs-on: ubuntu-latest
    needs: [ 'ct-deploy' ]
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run E2E e2e-tests
        uses: ./.github/actions/postman
        with:
          ct_client_id: ${{ secrets.CT_CLIENT_ID }}
          ct_secret: ${{ secrets.CT_CLIENT_SECRET }}
          postman_collection_json: "eagle-eye-e2e-tests.postman_collection.json"
          ct_region: ${{ vars.CT_REGION }}
          ct_project_id: ${{ vars.CT_PROJECT_KEY }}
          ee_client_id: ${{ secrets.EE_CLIENT_ID }}
          ee_client_secret: ${{ secrets.EE_CLIENT_SECRET }}
          ee_wallet_url: ${{ vars.EE_WALLET_URL }}
          ee_pos_url: ${{ vars.EE_POS_URL }}
          ee_resources_url: ${{ vars.EE_RESOURCES_URL }}
