name: E2E tests
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Run tests against
        required: true
        options:
          - dev
          - prod
jobs:
  e2e-tests:
    name: 'Running E2E tests'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run E2E e2e-tests
        run: echo "Placeholder text, E2E tests are running."