name: E2E tests
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Run tests against
        required: true
        options:
          - dev
          - staging
jobs:
  e2e-tests:
    name: 'Running E2E tests'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run E2E e2e-tests
        uses: ./.github/actions/postman
        with:
          ct_client_id: ${{ secrets.CT_CLIENT_ID }}
          ct_secret: ${{ secrets.CT_CLIENT_SECRET }}
          postman_collection_json: "eagle-eye-e2e-tests.postman_collection.json"
          ct_region: ${{ vars.CT_REGION }}
          ct_project_id: ${{ vars.CT_PROJECT_KEY }}